theme = "lynx"
title = "qrxnz's space"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Karol Skoczyk"
  headline = "I'm a computer enthusiast driven by a curiosity for how things workâ€”which often means taking them apart first. With a background soundtrack of math rock and progressive metal, I spend my free time writing blog posts, getting lost in books, and hitting the pavement on my aggressive inline skates ðŸ˜º \n Also making music since December 2025 :)"
  image = "img/avatar.jpg"
  links = [
    { link = { href = "https://blog.qrxnz.dev", text = "My Blog", target = "_self" } },
    { email = "mailto:send@qrxnz.dev" },
    { github = "https://github.com/qrxnz" },
    { link = { href = "https://linktr.ee/qrxnz", text = "Other Links...", target = "_self" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
